---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/maruiz93/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-main
